#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: LicenseRef-TRL-1.0
# Copyright (c) 2026 Alexander Romanov <alex.xorm@gmail.com>
# Tempo Research License v1.0 -- see LICENSE. Commercial use by agreement.
"""ПРОИСХОЖДЕНИЕ: число без метки происхождения -> отчёт НЕ СОБИРАЕТСЯ.

Это не педантизм, а лечение конкретной болезни.  «Наш собственный документ» -- НЕ то же, что
«наш собственный замер».  Число, у которого не названа база сравнения, -- не число: в этом
проекте отношение из чужой колонки таблицы прошло через памятку, сводку, постановку наряда и
отчёт агента, ни разу не встретив замера, потому что все четверо цитировали ОДИН источник.

Отсюда правило: если в отчёте есть число, у него обязан быть ЛИБО `plugin_id` (значит, это
ставка плагина со своим статусом), ЛИБО пометка «конвейерное» (значит, оно вычислено из
других, и их происхождение проверено рекурсивно).
"""

from __future__ import annotations


class ProvenanceError(Exception):
    pass


def require_provenance(report) -> None:
    if not getattr(report, "plugin_id", None):
        raise ProvenanceError(
            "отчёт не назвал плагин: неизвестно, чьи ставки участвовали в выводе"
        )
    for c in getattr(report, "comparisons", ()):
        if not getattr(c, "baseline", None):
            raise ProvenanceError("сравнение без названной базы -- это не число")
        if c.baseline.kind == "LIBRARY" and not c.baseline.what:
            raise ProvenanceError(
                "плечо-соперник названо, но не сказано ЧТО ИМЕННО оно меряет; "
                "именно так рождается сравнение с чужой колонкой"
            )
    for r in getattr(report, "rates_used", ()):
        st = getattr(r, "status", None)
        if st is None:
            raise ProvenanceError("ставка без статуса происхождения: %r" % (r,))
        if st == "MEASURED":
            prov = getattr(r, "prov", None)
            if prov is None or getattr(prov, "card", None) is None:
                raise ProvenanceError(
                    "ставка %s заявлена как MEASURED без карты -- это заявка на точность, "
                    "которой у неё нет" % getattr(r, "symbol", "?")
                )


def stamp(tempo_version: str, plugin_id: str, data_hash: str, date: str) -> str:
    """ШТАМП ПОРОЖДЕНИЯ -- четвёртая строка шапки в сгенерированных файлах."""
    return "Generated by tempo %s / plugin %s / data %s / %s" % (
        tempo_version,
        plugin_id,
        data_hash,
        date,
    )
